version: "3.2"

services:
  dev:
    container_name: gateway
    image: paritytech/ci-linux:production
    working_dir: /var/www/gateway
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/gateway/.cargo
      - WASM_BUILD_TOOLCHAIN=nightly-2020-09-27
    volumes:
      - .:/var/www/gateway
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/gateway --dev --ws-external"

  cross-compile:
    build: .
      args:
        PULL_FROM: arm64v8/ubuntu:20.04
    working_dir: /src
    command: sh