
gateway_user_home: /home/gateway
chain_data_dir: "{{ gateway_user_home }}/chain-data"
node_key_dir: "{{ gateway_user_home }}/.keys"
node_key_priv_file: "{{ node_key_dir }}/node_key"
node_key_pub_file: "{{ node_key_dir }}/node_key.pub"
fact_dir: "/etc/ansible/facts.d"
fact_file: "{{ fact_dir }}/substrate.fact"
rust_version: "nightly-2021-05-24"
