
- name: ensure a list of packages installed
  apt:
    pkg: "{{ packages }}"
    state: present
    update_cache: true
  become: 'yes'

- name: check for rustup
  stat:
    path: '{{ rustup_home }}'
  changed_when: false
  register: rustup_home_binary

- when: not rustup_home_binary.stat.exists
  block:
    - name: download rustup-init...
      get_url:
        url: '{{ rustup_init_url }}'
        dest: /tmp/rustup-init
        mode: 0755

    - name: install rust...
      command: /tmp/rustup-init -y
      args:
        creates: '{{ rustup_home }}'

    - name: install stable rust
      command: '{{ rustup_home }} default stable'

    - name: install nightly toolchain
      command: '{{ rustup_home }} toolchain install nightly'

    - name: install wasm
      command: '{{ rustup_home }} target add wasm32-unknown-unknown --toolchain nightly'

  always:
    - name: clean rustup
      file:
        path: /tmp/rustup-init
        state: absent
