
- name: Add system accounts
  import_tasks: system-accounts.yml

- name: Install build essentials
  import_tasks: build-essentials.yml

- name: Build chain
  import_tasks: build-chain.yml

- name: Generate keys
  import_tasks: generate-keys.yml

- name: Install Gateway Service
  import_tasks: gateway-service.yml
