[package]
authors = ['Compound <https://compound.finance>']
build = 'build.rs'
description = 'A Compound Chain node.'
edition = '2018'
homepage = 'https://compound.cash'
name = 'compound-chain'
repository = 'https://github.com/compound-finance/compound-chain/'
version = '1.0.0'
default-run = "compound-chain"

[[bin]]
name = 'compound-chain'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[build-dependencies]
substrate-build-script-utils = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git'}

[dependencies]
hex = "0.4.2"
jsonrpc-core = '15.0.0'
structopt = '0.3.8'
futures = { version = "0.3.1", features = ["compat"] }

codec = { package = "parity-scale-codec", version = "1.3.4" }
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.58"
wasm-timer = "0.2"

# Substrate dependencies
sc-chain-spec = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
sc-client-api = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
sc-cli = { version = '0.8.0', git = 'https://github.com/compound-finance/substrate.git', features = ['wasmtime'] }
sc-client-db = { version = "0.8.0", git = 'https://github.com/compound-finance/substrate.git', default-features = false }
sp-core = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
sc-consensus = { version = '0.8.0', git = 'https://github.com/compound-finance/substrate.git' }
sp-consensus = { version = '0.8.0', git = 'https://github.com/compound-finance/substrate.git' }
sc-consensus-aura = { version = '0.8.0', git = 'https://github.com/compound-finance/substrate.git' }
sp-consensus-aura = { version = '0.8.0', git = 'https://github.com/compound-finance/substrate.git' }
sc-consensus-epochs = { version = '0.8.0', git = 'https://github.com/compound-finance/substrate.git' }
sc-consensus-slots = { version = '0.8.0', git = 'https://github.com/compound-finance/substrate.git' }
sc-finality-grandpa = { version = '0.8.0', git = 'https://github.com/compound-finance/substrate.git' }
sc-finality-grandpa-rpc = { version = '0.8.0', git = 'https://github.com/compound-finance/substrate.git' }
sp-finality-grandpa = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
sc-executor = { version = '0.8.0', git = 'https://github.com/compound-finance/substrate.git', features = ['wasmtime'] }
sp-inherents = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
sc-keystore = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
sp-keystore = { version = '0.8.0', git = 'https://github.com/compound-finance/substrate.git' }
sc-network = { version = '0.8.0', git = 'https://github.com/compound-finance/substrate.git' }
sp-runtime = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
sc-service = { version = '0.8.0', git = 'https://github.com/compound-finance/substrate.git', default-features = false, features = [] }
sc-transaction-pool = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
sp-transaction-pool = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }

# These dependencies are used for the node's RPCs
sc-rpc = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
sp-api = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
sc-rpc-api = { version = '0.8.0', git = 'https://github.com/compound-finance/substrate.git' }
sp-blockchain = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
sp-chain-spec = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
sp-block-builder = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
sc-basic-authorship = { version = '0.8.0', git = 'https://github.com/compound-finance/substrate.git' }
sc-sync-state-rpc = { version = '0.8.0', git = 'https://github.com/compound-finance/substrate.git' }
substrate-frame-rpc-system = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
pallet-transaction-payment-rpc = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }

# Used only for runtime benchmarking
frame-benchmarking = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
frame-benchmarking-cli = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git', default-features = false, optional = true }

# Local dependencies
compound-chain-runtime = { path = '../runtime' }
compound-crypto = { path = '../compound-crypto' }
our-std = { path = '../our-std' }
pallet-cash = { path = '../pallets/cash' }
runtime-interfaces = { path = '../pallets/runtime-interfaces' }

[dev-dependencies]
tempfile = "3.1.0"

sc-consensus-aura = { version = '0.8.0', git = 'https://github.com/compound-finance/substrate.git' }
sp-keyring = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }
sc-service-test = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git', default-features = false, features = [] }
sp-timestamp = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git', default-features = false }

frame-system = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }

pallet-transaction-payment = { version = '2.0.0', git = 'https://github.com/compound-finance/substrate.git' }

[features]
default = ['with-parity-db']
with-parity-db=['sc-client-db/with-parity-db']
with-rocks-db=['sc-client-db/with-kvdb-rocksdb']
runtime-benchmarks = [
	'compound-chain-runtime/runtime-benchmarks',
	'frame-benchmarking-cli',
]
runtime-debug = ['our-std/runtime-debug']
